"""remove unused homepage json sections

Revision ID: 03d67c34c781
Revises: 6869337dad76
Create Date: 2026-07-22 15:25:34.165754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03d67c34c781'
down_revision: Union[str, Sequence[str], None] = '6869337dad76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homepage', 'why_choose_us')
    op.drop_column('homepage', 'industries')
    op.drop_column('homepage', 'testimonials')
    op.drop_column('homepage', 'faq')
    op.drop_column('homepage', 'stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homepage', sa.Column('stats', mysql.JSON(), nullable=False))
    op.add_column('homepage', sa.Column('faq', mysql.JSON(), nullable=False))
    op.add_column('homepage', sa.Column('testimonials', mysql.JSON(), nullable=False))
    op.add_column('homepage', sa.Column('industries', mysql.JSON(), nullable=False))
    op.add_column('homepage', sa.Column('why_choose_us', mysql.JSON(), nullable=False))
    # ### end Alembic commands ###
