"""create homepage table

Revision ID: 1a5b1f679d6a
Revises: b9a4b978e602
Create Date: 2026-07-22 13:48:25.467432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5b1f679d6a'
down_revision: Union[str, Sequence[str], None] = 'b9a4b978e602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_badge', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.Text(), nullable=False),
    sa.Column('hero_description', sa.Text(), nullable=False),
    sa.Column('primary_button_text', sa.String(length=100), nullable=False),
    sa.Column('primary_button_url', sa.String(length=255), nullable=False),
    sa.Column('secondary_button_text', sa.String(length=100), nullable=False),
    sa.Column('secondary_button_url', sa.String(length=255), nullable=False),
    sa.Column('cta_title', sa.Text(), nullable=False),
    sa.Column('cta_description', sa.Text(), nullable=False),
    sa.Column('cta_button_text', sa.String(length=100), nullable=False),
    sa.Column('cta_button_url', sa.String(length=255), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_id'), 'homepage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepage_id'), table_name='homepage')
    op.drop_table('homepage')
    # ### end Alembic commands ###
