"""create missing cms support tables

Revision ID: 5062da617f74
Revises: 5f8c2e7a91bd
Create Date: 2026-08-06 13:02:28.172496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5062da617f74'
down_revision: Union[str, Sequence[str], None] = '5f8c2e7a91bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_badge', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.String(length=500), nullable=False),
    sa.Column('hero_description', sa.Text(), nullable=False),
    sa.Column('overview_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('overview_title', sa.String(length=500), nullable=False),
    sa.Column('overview_description_one', sa.Text(), nullable=False),
    sa.Column('overview_description_two', sa.Text(), nullable=False),
    sa.Column('values_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('values_title', sa.String(length=500), nullable=False),
    sa.Column('values_description', sa.String(length=500), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.String(length=500), nullable=False),
    sa.Column('show_hero', sa.Boolean(), nullable=False),
    sa.Column('show_overview', sa.Boolean(), nullable=False),
    sa.Column('show_values', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_page_id'), 'about_page', ['id'], unique=False)
    op.create_table('about_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_stats_id'), 'about_stats', ['id'], unique=False)
    op.create_table('about_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_values_id'), 'about_values', ['id'], unique=False)
    op.create_table('blog_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.String(length=500), nullable=False),
    sa.Column('hero_description', sa.String(length=1000), nullable=False),
    sa.Column('search_placeholder', sa.String(length=255), nullable=False),
    sa.Column('all_categories_label', sa.String(length=150), nullable=False),
    sa.Column('clear_filters_text', sa.String(length=150), nullable=False),
    sa.Column('empty_title', sa.String(length=255), nullable=False),
    sa.Column('empty_description', sa.String(length=500), nullable=False),
    sa.Column('filtered_empty_description', sa.String(length=500), nullable=False),
    sa.Column('read_button_text', sa.String(length=150), nullable=False),
    sa.Column('author_prefix', sa.String(length=100), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.String(length=500), nullable=False),
    sa.Column('show_hero', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_filters', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_articles', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_author', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_date', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_page_id'), 'blog_page', ['id'], unique=False)
    op.create_table('career_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.String(length=500), nullable=False),
    sa.Column('hero_description', sa.String(length=1000), nullable=False),
    sa.Column('openings_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('openings_title', sa.String(length=500), nullable=False),
    sa.Column('openings_description', sa.String(length=1000), nullable=False),
    sa.Column('empty_title', sa.String(length=255), nullable=False),
    sa.Column('empty_description', sa.String(length=500), nullable=False),
    sa.Column('apply_button_text', sa.String(length=100), nullable=False),
    sa.Column('application_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('application_title_prefix', sa.String(length=255), nullable=False),
    sa.Column('application_description', sa.String(length=500), nullable=False),
    sa.Column('full_name_label', sa.String(length=100), nullable=False),
    sa.Column('email_label', sa.String(length=100), nullable=False),
    sa.Column('phone_label', sa.String(length=100), nullable=False),
    sa.Column('position_label', sa.String(length=100), nullable=False),
    sa.Column('experience_label', sa.String(length=100), nullable=False),
    sa.Column('company_label', sa.String(length=100), nullable=False),
    sa.Column('location_label', sa.String(length=100), nullable=False),
    sa.Column('linkedin_label', sa.String(length=100), nullable=False),
    sa.Column('resume_label', sa.String(length=100), nullable=False),
    sa.Column('cover_letter_label', sa.String(length=100), nullable=False),
    sa.Column('resume_upload_title', sa.String(length=150), nullable=False),
    sa.Column('resume_upload_description', sa.String(length=255), nullable=False),
    sa.Column('cancel_button_text', sa.String(length=100), nullable=False),
    sa.Column('submit_button_text', sa.String(length=100), nullable=False),
    sa.Column('submitting_button_text', sa.String(length=100), nullable=False),
    sa.Column('success_message', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.String(length=500), nullable=False),
    sa.Column('show_hero', sa.Boolean(), nullable=False),
    sa.Column('show_openings', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_page_id'), 'career_page', ['id'], unique=False)
    op.create_table('case_studies_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.String(length=500), nullable=False),
    sa.Column('hero_description', sa.String(length=1000), nullable=False),
    sa.Column('search_placeholder', sa.String(length=255), nullable=False),
    sa.Column('all_industries_label', sa.String(length=150), nullable=False),
    sa.Column('clear_filters_text', sa.String(length=150), nullable=False),
    sa.Column('empty_title', sa.String(length=255), nullable=False),
    sa.Column('empty_description', sa.String(length=500), nullable=False),
    sa.Column('filtered_empty_description', sa.String(length=500), nullable=False),
    sa.Column('results_heading', sa.String(length=150), nullable=False),
    sa.Column('view_button_text', sa.String(length=150), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.String(length=500), nullable=False),
    sa.Column('show_hero', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_filters', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_case_studies', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_results', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_technologies', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_studies_page_id'), 'case_studies_page', ['id'], unique=False)
    op.create_table('contact_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.String(length=500), nullable=False),
    sa.Column('hero_description', sa.String(length=1000), nullable=False),
    sa.Column('form_title', sa.String(length=255), nullable=False),
    sa.Column('form_description', sa.String(length=500), nullable=False),
    sa.Column('full_name_label', sa.String(length=100), nullable=False),
    sa.Column('email_label', sa.String(length=100), nullable=False),
    sa.Column('company_label', sa.String(length=100), nullable=False),
    sa.Column('phone_label', sa.String(length=100), nullable=False),
    sa.Column('service_label', sa.String(length=100), nullable=False),
    sa.Column('message_label', sa.String(length=100), nullable=False),
    sa.Column('service_placeholder', sa.String(length=150), nullable=False),
    sa.Column('submit_button_text', sa.String(length=100), nullable=False),
    sa.Column('submitting_button_text', sa.String(length=100), nullable=False),
    sa.Column('success_message', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.String(length=500), nullable=False),
    sa.Column('show_breadcrumb', sa.Boolean(), nullable=False),
    sa.Column('show_form', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_page_id'), 'contact_page', ['id'], unique=False)
    op.create_table('footer_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('open_in_new_tab', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footer_links_display_order'), 'footer_links', ['display_order'], unique=False)
    op.create_index(op.f('ix_footer_links_group_name'), 'footer_links', ['group_name'], unique=False)
    op.create_index(op.f('ix_footer_links_id'), 'footer_links', ['id'], unique=False)
    op.create_index(op.f('ix_footer_links_is_visible'), 'footer_links', ['is_visible'], unique=False)
    op.create_table('job_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_openings_id'), 'job_openings', ['id'], unique=False)
    op.create_index(op.f('ix_job_openings_slug'), 'job_openings', ['slug'], unique=True)
    op.create_table('navigation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('open_in_new_tab', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navigation_items_display_order'), 'navigation_items', ['display_order'], unique=False)
    op.create_index(op.f('ix_navigation_items_id'), 'navigation_items', ['id'], unique=False)
    op.create_index(op.f('ix_navigation_items_is_visible'), 'navigation_items', ['is_visible'], unique=False)
    op.create_table('services_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_badge', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.String(length=500), nullable=False),
    sa.Column('hero_highlight', sa.String(length=255), nullable=False),
    sa.Column('hero_description', sa.String(length=1000), nullable=False),
    sa.Column('primary_button_text', sa.String(length=100), nullable=False),
    sa.Column('primary_button_url', sa.String(length=500), nullable=False),
    sa.Column('secondary_button_text', sa.String(length=100), nullable=False),
    sa.Column('secondary_button_url', sa.String(length=500), nullable=False),
    sa.Column('hero_feature_one', sa.String(length=150), nullable=False),
    sa.Column('hero_feature_two', sa.String(length=150), nullable=False),
    sa.Column('hero_feature_three', sa.String(length=150), nullable=False),
    sa.Column('hero_feature_four', sa.String(length=150), nullable=False),
    sa.Column('services_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('services_title', sa.String(length=500), nullable=False),
    sa.Column('services_description', sa.String(length=1000), nullable=False),
    sa.Column('services_empty_title', sa.String(length=255), nullable=False),
    sa.Column('services_empty_description', sa.String(length=500), nullable=False),
    sa.Column('service_button_text', sa.String(length=100), nullable=False),
    sa.Column('benefits_badge', sa.String(length=255), nullable=False),
    sa.Column('benefits_title', sa.String(length=500), nullable=False),
    sa.Column('benefits_description', sa.String(length=1000), nullable=False),
    sa.Column('process_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('process_title', sa.String(length=500), nullable=False),
    sa.Column('process_description', sa.String(length=1000), nullable=False),
    sa.Column('industries_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('industries_title', sa.String(length=500), nullable=False),
    sa.Column('industries_description', sa.String(length=1000), nullable=False),
    sa.Column('cta_title', sa.String(length=500), nullable=False),
    sa.Column('cta_description', sa.String(length=1000), nullable=False),
    sa.Column('cta_primary_button_text', sa.String(length=100), nullable=False),
    sa.Column('cta_primary_button_url', sa.String(length=500), nullable=False),
    sa.Column('cta_secondary_button_text', sa.String(length=100), nullable=False),
    sa.Column('cta_secondary_button_url', sa.String(length=500), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.String(length=500), nullable=False),
    sa.Column('show_hero', sa.Boolean(), nullable=False),
    sa.Column('show_services', sa.Boolean(), nullable=False),
    sa.Column('show_benefits', sa.Boolean(), nullable=False),
    sa.Column('show_process', sa.Boolean(), nullable=False),
    sa.Column('show_stats', sa.Boolean(), nullable=False),
    sa.Column('show_industries', sa.Boolean(), nullable=False),
    sa.Column('show_cta', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_page_id'), 'services_page', ['id'], unique=False)
    op.create_table('technology_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_badge', sa.String(length=255), nullable=False),
    sa.Column('hero_title', sa.String(length=500), nullable=False),
    sa.Column('hero_description', sa.String(length=1000), nullable=False),
    sa.Column('featured_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('featured_title', sa.String(length=500), nullable=False),
    sa.Column('featured_description', sa.String(length=1000), nullable=False),
    sa.Column('categories_eyebrow', sa.String(length=255), nullable=False),
    sa.Column('categories_title', sa.String(length=500), nullable=False),
    sa.Column('categories_description', sa.String(length=1000), nullable=False),
    sa.Column('empty_title', sa.String(length=255), nullable=False),
    sa.Column('empty_description', sa.String(length=500), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.String(length=500), nullable=False),
    sa.Column('show_hero', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_featured', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_categories', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_page_id'), 'technology_page', ['id'], unique=False)
    op.add_column('homepage', sa.Column('show_hero', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('services_title', sa.String(length=255), nullable=False))
    op.add_column('homepage', sa.Column('services_description', sa.String(length=500), nullable=False))
    op.add_column('homepage', sa.Column('show_services', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('technologies_title', sa.String(length=255), nullable=False))
    op.add_column('homepage', sa.Column('technologies_description', sa.String(length=500), nullable=False))
    op.add_column('homepage', sa.Column('show_technologies', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('benefits_title', sa.String(length=255), nullable=False))
    op.add_column('homepage', sa.Column('benefits_description', sa.String(length=500), nullable=False))
    op.add_column('homepage', sa.Column('show_benefits', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('industries_title', sa.String(length=255), nullable=False))
    op.add_column('homepage', sa.Column('industries_description', sa.String(length=500), nullable=False))
    op.add_column('homepage', sa.Column('show_industries', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('case_studies_title', sa.String(length=255), nullable=False))
    op.add_column('homepage', sa.Column('case_studies_description', sa.String(length=500), nullable=False))
    op.add_column('homepage', sa.Column('show_case_studies', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('testimonials_title', sa.String(length=255), nullable=False))
    op.add_column('homepage', sa.Column('testimonials_description', sa.String(length=500), nullable=False))
    op.add_column('homepage', sa.Column('show_testimonials', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('stats_title', sa.String(length=255), nullable=False))
    op.add_column('homepage', sa.Column('stats_description', sa.String(length=500), nullable=False))
    op.add_column('homepage', sa.Column('show_stats', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('faq_title', sa.String(length=255), nullable=False))
    op.add_column('homepage', sa.Column('faq_description', sa.String(length=500), nullable=False))
    op.add_column('homepage', sa.Column('show_faq', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('show_cta', sa.Boolean(), nullable=False))
    op.add_column('homepage', sa.Column('section_order', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Intentionally non-destructive.
    #
    # These tables and columns existed in some
    # installations before this corrective
    # revision was introduced. Dropping them
    # could destroy valid application data.
    pass
