"""create homepage stats table

Revision ID: 937c1749a600
Revises: 03d67c34c781
Create Date: 2026-07-22 15:27:56.227787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937c1749a600'
down_revision: Union[str, Sequence[str], None] = '03d67c34c781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_stats_id'), 'homepage_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepage_stats_id'), table_name='homepage_stats')
    op.drop_table('homepage_stats')
    # ### end Alembic commands ###
