"""add read status to contacts

Revision ID: dced098c71f6
Revises: 4aa8aacc6feb
Create Date: 2026-07-20 14:13:30.746273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dced098c71f6"
down_revision: Union[str, Sequence[str], None] = "4aa8aacc6feb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column("is_read", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "is_read")
    # ### end Alembic commands ###
