"""create career applications table

Revision ID: e4fb2663f80d
Revises: 59e024aa43b6
Create Date: 2026-07-21 12:12:59.334461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e4fb2663f80d"
down_revision: Union[str, Sequence[str], None] = "59e024aa43b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("position", sa.String(length=150), nullable=False),
        sa.Column("experience", sa.String(length=100), nullable=True),
        sa.Column("current_company", sa.String(length=150), nullable=True),
        sa.Column("location", sa.String(length=150), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("resume_url", sa.String(length=500), nullable=True),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="new", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_career_applications_email"),
        "career_applications",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_applications_id"), "career_applications", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_career_applications_id"), table_name="career_applications")
    op.drop_index(
        op.f("ix_career_applications_email"), table_name="career_applications"
    )
    op.drop_table("career_applications")
    # ### end Alembic commands ###
